services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - orders-service
      - payments-service

  orders-service:
    build: ./orders-service
    depends_on:
      - db-orders
      - rabbitmq

  payments-service:
    build: ./payments-service
    depends_on:
      - db-payments
      - rabbitmq

  db-orders:
    image: postgres:15
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"

  db-payments:
    image: postgres:15
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"