// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: analysis.proto

package analysis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFileRequest) Reset() {
	*x = AnalyzeFileRequest{}
	mi := &file_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileRequest) ProtoMessage() {}

func (x *AnalyzeFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFileRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type AnalyzeFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paragraphs    int32                  `protobuf:"varint,1,opt,name=paragraphs,proto3" json:"paragraphs,omitempty"`
	Words         int32                  `protobuf:"varint,2,opt,name=words,proto3" json:"words,omitempty"`
	Characters    int32                  `protobuf:"varint,3,opt,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFileResponse) Reset() {
	*x = AnalyzeFileResponse{}
	mi := &file_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFileResponse) ProtoMessage() {}

func (x *AnalyzeFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFileResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFileResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeFileResponse) GetParagraphs() int32 {
	if x != nil {
		return x.Paragraphs
	}
	return 0
}

func (x *AnalyzeFileResponse) GetWords() int32 {
	if x != nil {
		return x.Words
	}
	return 0
}

func (x *AnalyzeFileResponse) GetCharacters() int32 {
	if x != nil {
		return x.Characters
	}
	return 0
}

type WordCloudRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCloudRequest) Reset() {
	*x = WordCloudRequest{}
	mi := &file_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCloudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCloudRequest) ProtoMessage() {}

func (x *WordCloudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCloudRequest.ProtoReflect.Descriptor instead.
func (*WordCloudRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *WordCloudRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type WordCloudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // PNG image bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCloudResponse) Reset() {
	*x = WordCloudResponse{}
	mi := &file_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCloudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCloudResponse) ProtoMessage() {}

func (x *WordCloudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCloudResponse.ProtoReflect.Descriptor instead.
func (*WordCloudResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *WordCloudResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_analysis_proto protoreflect.FileDescriptor

const file_analysis_proto_rawDesc = "" +
	"\n" +
	"\x0eanalysis.proto\x12\x05proto\"-\n" +
	"\x12AnalyzeFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"k\n" +
	"\x13AnalyzeFileResponse\x12\x1e\n" +
	"\n" +
	"paragraphs\x18\x01 \x01(\x05R\n" +
	"paragraphs\x12\x14\n" +
	"\x05words\x18\x02 \x01(\x05R\x05words\x12\x1e\n" +
	"\n" +
	"characters\x18\x03 \x01(\x05R\n" +
	"characters\"+\n" +
	"\x10WordCloudRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\")\n" +
	"\x11WordCloudResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image2\x9f\x01\n" +
	"\x0fAnalysisService\x12D\n" +
	"\vAnalyzeFile\x12\x19.proto.AnalyzeFileRequest\x1a\x1a.proto.AnalyzeFileResponse\x12F\n" +
	"\x11GenerateWordCloud\x12\x17.proto.WordCloudRequest\x1a\x18.proto.WordCloudResponseB0Z.github.com/w1sq/SWE/BHW2/api/analysis;analysisb\x06proto3"

var (
	file_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_rawDescData []byte
)

func file_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)))
	})
	return file_analysis_proto_rawDescData
}

var file_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_analysis_proto_goTypes = []any{
	(*AnalyzeFileRequest)(nil),  // 0: proto.AnalyzeFileRequest
	(*AnalyzeFileResponse)(nil), // 1: proto.AnalyzeFileResponse
	(*WordCloudRequest)(nil),    // 2: proto.WordCloudRequest
	(*WordCloudResponse)(nil),   // 3: proto.WordCloudResponse
}
var file_analysis_proto_depIdxs = []int32{
	0, // 0: proto.AnalysisService.AnalyzeFile:input_type -> proto.AnalyzeFileRequest
	2, // 1: proto.AnalysisService.GenerateWordCloud:input_type -> proto.WordCloudRequest
	1, // 2: proto.AnalysisService.AnalyzeFile:output_type -> proto.AnalyzeFileResponse
	3, // 3: proto.AnalysisService.GenerateWordCloud:output_type -> proto.WordCloudResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analysis_proto_init() }
func file_analysis_proto_init() {
	if File_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto = out.File
	file_analysis_proto_goTypes = nil
	file_analysis_proto_depIdxs = nil
}
