// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: file-storage.proto

package filestorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileRequest) Reset() {
	*x = StoreFileRequest{}
	mi := &file_file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileRequest) ProtoMessage() {}

func (x *StoreFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileRequest.ProtoReflect.Descriptor instead.
func (*StoreFileRequest) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StoreFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StoreFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StoreFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreFileResponse) Reset() {
	*x = StoreFileResponse{}
	mi := &file_file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreFileResponse) ProtoMessage() {}

func (x *StoreFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreFileResponse.ProtoReflect.Descriptor instead.
func (*StoreFileResponse) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StoreFileResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_file_storage_proto protoreflect.FileDescriptor

const file_file_storage_proto_rawDesc = "" +
	"\n" +
	"\x12file-storage.proto\x12\x05proto\"H\n" +
	"\x10StoreFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\",\n" +
	"\x11StoreFileResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\")\n" +
	"\x0eGetFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"G\n" +
	"\x0fGetFileResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent2\x8e\x01\n" +
	"\x12FileStoringService\x12>\n" +
	"\tStoreFile\x12\x17.proto.StoreFileRequest\x1a\x18.proto.StoreFileResponse\x128\n" +
	"\aGetFile\x12\x15.proto.GetFileRequest\x1a\x16.proto.GetFileResponseB7Z5github.com/w1sq/SWE/BHW2/api/file-storage;filestorageb\x06proto3"

var (
	file_file_storage_proto_rawDescOnce sync.Once
	file_file_storage_proto_rawDescData []byte
)

func file_file_storage_proto_rawDescGZIP() []byte {
	file_file_storage_proto_rawDescOnce.Do(func() {
		file_file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_storage_proto_rawDesc), len(file_file_storage_proto_rawDesc)))
	})
	return file_file_storage_proto_rawDescData
}

var file_file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_file_storage_proto_goTypes = []any{
	(*StoreFileRequest)(nil),  // 0: proto.StoreFileRequest
	(*StoreFileResponse)(nil), // 1: proto.StoreFileResponse
	(*GetFileRequest)(nil),    // 2: proto.GetFileRequest
	(*GetFileResponse)(nil),   // 3: proto.GetFileResponse
}
var file_file_storage_proto_depIdxs = []int32{
	0, // 0: proto.FileStoringService.StoreFile:input_type -> proto.StoreFileRequest
	2, // 1: proto.FileStoringService.GetFile:input_type -> proto.GetFileRequest
	1, // 2: proto.FileStoringService.StoreFile:output_type -> proto.StoreFileResponse
	3, // 3: proto.FileStoringService.GetFile:output_type -> proto.GetFileResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_storage_proto_init() }
func file_file_storage_proto_init() {
	if File_file_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_storage_proto_rawDesc), len(file_file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_storage_proto_goTypes,
		DependencyIndexes: file_file_storage_proto_depIdxs,
		MessageInfos:      file_file_storage_proto_msgTypes,
	}.Build()
	File_file_storage_proto = out.File
	file_file_storage_proto_goTypes = nil
	file_file_storage_proto_depIdxs = nil
}
